### ISSUE TITLE
v0.1 TODO

### ISSUE THREAD

**Issue by c42f** [c42f/MicroLogging.jl#2]
After great discussion and feedback with a lot of people at juliacon, and having described some of the remaining problems, the package probably needs the following before an initial release -

* [x] ~~Sort out the default backend using `display()`, less metadata by default, and a bit less yucky hackery.~~ *Will do later*.
* [x] Sort out efficient dynamically scoped lookup of the initial log filtering predicate.
* [x] Move the closure capture workaround to FastClosures,jl and register that package
* [x] ~~Kill off custom log levels?~~  *Concrete early filtering implies these should be kept.*
